### PR TITLE
Added ability to output to Json

### PR DESCRIPTION
**Pull request by osmanzeki**
Hey @richorama, first thanks for this building utility. I've been looking to build something like this for a little while and yours had the right tech and simplicity for me to use and now contribute to.

# New `json` output format
I've taken the liberty of making a version of this that allows the user to output in a `json` format (mostly to be able to interpret the data visually in a different context. Personally, I was thinking about using this data in a Jupyter Notebook perhaps to visualize some of this data for myself using Python (although I think one can also use C# in Jupyter now).

# Updated Dependencies

I've updated the project to use `DotNet Core 3.0+` and updated to the lasted stable version of `LibGitSharp 0.26.2` too. I decided to go for the latest version of dotnet to be able to use the new native `System.Text.Json` features of the framework instead of adding a new dependency.

---

You definitely don't have to merge this as the original utility works perfectly fine without this in my opinion but I figured I might as well share it back in case you felt it was a useful addition too.

Thanks again for making this in the first place.

⏲️ ⏳ 🚀

### CODE REVIEW

**Comment by osmanzeki** [comment]
I'm also looking at making it output a single trimmed binary as outlined here:
https://www.hanselman.com/blog/MakingATinyNETCore30EntirelySelfcontainedSingleExecutable.aspx

Perhaps the merge could wait for this change as well.

**Comment by richorama** [comment]
Hi @osmanzeki thanks for your interest in this project! These contributions look great, I'll take a look at them tomorrow.

**Comment by osmanzeki** [comment]
> I'm also looking at making it output a single trimmed binary as outlined here:
> https://www.hanselman.com/blog/MakingATinyNETCore30EntirelySelfcontainedSingleExecutable.aspx
> 
> Perhaps the merge could wait for this change as well.

I realize now that this can totally be left to the developer to decide actually so I won't do anything in the repo itself here.

> Hi @osmanzeki thanks for your interest in this project! These contributions look great, I'll take a look at them tomorrow.

Allright. :)

**Comment by richorama** [comment]
Awesome, thank you!

**Pull request merged**
